{{config(tags=['ai'])}}
SELECT
    RE.TOPIC,
    SR.CITY,
    RE.SENTIMENT,
    COUNT(*) AS REVIEWS,
    ROUND(AVG(RE.SENTIMENT_SCORE),3) AS AVERAGE_SENTIMENT_SCORE,
    ROUND(AVG(SR.RATING),3) AS AVERAGE_RATING,
    COUNT_IF(RE.KEY_ISSUES IS NOT NULL ) AS FLAGGED_ISSUES
FROM 
    {{source('ai', 'review_enriched')}} AS RE
INNER JOIN {{ref('stg_reviews')}} AS SR USING (REVIEW_ID)
GROUP BY 1, 2, 3